[package]
name  = "gr"
version = "0.0.0"
authors = ["Mark S. Baranowski"]
build="build.rs"
links="gaol"

[lib]
name = "gr"
path = "src/gaol.rs"

[dependencies]
libc = "0.1"

[build-dependencies]
gcc = "0.3"

