[package]
name  = "ga"
version = "0.0.1"
authors = ["Andy Schwartzmeyer (modified by Mark S. Baranowski)"]

[lib]
name = "ga"
path = "algorithm.rs"

[dependencies]
rand = "0.3"

[dependencies.gu]
path = "../.."

[dependencies.gr]
path = "../.."