[package]
name = "gelpia"
version = "0.0.1"
authors = ["Mark S. Baranowski <mark.s.baranowski@gmail.com>", "Ian Briggs <ibriggs@comcast.net>"]

[[bin]]
name = "cooperative"
path = "src/bin/cooperative.rs"

[[bin]]
name = "serial"
path = "src/main.rs"

[dependencies.gelpia_utils]
path = "src/gelpia_utils"

[dependencies.gr]
path = "src/gaol"

[dependencies]
#threadpool = "0.1"
getopts = "0.2.*"
rand = "0.3.*"
time = "*"

[dependencies.ga]
path = "src/ga"

[dependencies.args]
path = "src/args"

[dependencies.function]
path = "src/function"

[profile.release]
opt-level = 3
debug = false
rpath = false
#lto = true
debug-assertions = false
codegen-units = 1
