[package]
name = "gelpia"
version = "0.0.0"
authors = ["Mark S. Baranowski <mark.s.baranowski@gmail.com>", "Ian Briggs <ibriggs@comcast.net>"]
build = "build.rs"

[[bin]]
name = "cooperative"
path = "src/bin/cooperative.rs"

[[bin]]
name = "serial"
path = "src/main.rs"

[dependencies.gu]
path = "src/gu"

[dependencies.gr]
path = "src/gaol"

[dependencies]
threadpool = "0.1"
rand = "0.3"
getopts = "0.2"

[dependencies.ga]
path = "src/ga"

[dependencies.function]
path = "src/function"

[profile.release]
opt-level = 3
debug = false
rpath = false
#lto = true
debug-assertions = false
codegen-units = 1
