name: Python application

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install flex bison wget python3
        python3 -m pip install --upgrade pip
        pip3 install sly
    - name: Build requirements
      run: |
        make requirements -j2
    - name: Build gelpia
      run: |
        make -j2
    - name: Get gelpia_tests
      run: |
        git clone https://github.com/soarlab/gelpia_tests.git
        cd gelpia_tests
        git checkout version_2
        make
    - name: Run tests
      run: |
        cd gelpia_tests
        TESTER_ARGS="-v" make test